nodeLinker: node-modules

# Publish @ghs-hazard-pictograms/* packages to the public npm registry.
npmScopes:
  ghs-hazard-pictograms:
    npmRegistryServer: "https://registry.npmjs.org/"
    npmAuthToken: "${NPM_JS_AUTH:-}"
