// @ts-check
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import prettierConfig from 'eslint-config-prettier';
import storybook from 'eslint-plugin-storybook';
import { defineConfig, globalIgnores } from 'eslint/config';

export default defineConfig([
  // Ignore generated and build artefacts
  globalIgnores([
    'dist/**',
    'node_modules/**',
    'coverage/**',
    'data/**',
    // Storybook static build output
    '**/storybook-static/**',
    // Assets (generated by 'yarn update')
    'packages/@ghs-hazard-pictograms/assets/assets/**',
    // Auto-generated source files
    'packages/@ghs-hazard-pictograms/core/src/pictograms.generated.ts',
    'packages/@ghs-hazard-pictograms/react/src/PictogramProps.ts',
    'packages/@ghs-hazard-pictograms/react/src/Ghs*.tsx',
    'packages/@ghs-hazard-pictograms/react/src/Class*.tsx',
    'packages/@ghs-hazard-pictograms/react/src/Division*.tsx',
    'packages/@ghs-hazard-pictograms/react/src/Divisions*.tsx',
    'packages/@ghs-hazard-pictograms/react/src/index.ts',
    // CSS sprite (generated by 'yarn update')
    'packages/@ghs-hazard-pictograms/css/sprite.css',
    // Legacy root-level storybook config (storybook moved to apps/storybook/)
    '.storybook/**',
    // Legacy src/ (kept for reference during migration)
    'src/**',
  ]),

  // TypeScript files — bin/, packages/, and apps/
  {
    files: [
      'bin/**/*.ts',
      'packages/@ghs-hazard-pictograms/*/src/**/*.ts',
      'packages/@ghs-hazard-pictograms/*/src/**/*.tsx',
      'apps/storybook/src/**/*.ts',
      'apps/storybook/src/**/*.tsx',
      'apps/storybook/.storybook/**/*.ts',
    ],
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      // TypeScript recommended rules
      ...tsPlugin.configs.recommended.rules,

      // Quality rules
      'no-console': 'off', // bin scripts use console liberally
      'no-await-in-loop': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // JavaScript config files
  {
    files: ['*.mjs', '*.js', '**/jest.config.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      'no-undef': 'off',
    },
  },

  // Storybook stories
  ...storybook.configs['flat/recommended'],

  // Disable all Prettier-conflicting formatting rules (must be last)
  prettierConfig,
]);
